// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPW-XMwFornw4quAgq7IRllqqGrswB_zo',
    appId: '1:572161382320:web:dd98e458d50806b070e875',
    messagingSenderId: '572161382320',
    projectId: 'itm-connect-c864a',
    authDomain: 'itm-connect-c864a.firebaseapp.com',
    storageBucket: 'itm-connect-c864a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIMSgLgcw-bpm8wNlbPbCTSIk5GzPz2U',
    appId: '1:572161382320:android:26cde86002900a8e70e875',
    messagingSenderId: '572161382320',
    projectId: 'itm-connect-c864a',
    storageBucket: 'itm-connect-c864a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwDgHK-ntRXivIUeaLj6JEJRBYoI5CDUg',
    appId: '1:572161382320:ios:b43f62a6f1e83baf70e875',
    messagingSenderId: '572161382320',
    projectId: 'itm-connect-c864a',
    storageBucket: 'itm-connect-c864a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPW-XMwFornw4quAgq7IRllqqGrswB_zo',
    appId: '1:572161382320:web:4636b470181688b370e875',
    messagingSenderId: '572161382320',
    projectId: 'itm-connect-c864a',
    authDomain: 'itm-connect-c864a.firebaseapp.com',
    storageBucket: 'itm-connect-c864a.firebasestorage.app',
  );
}
